services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ${NEXTCLOUD_STACK_DIR}/db:/var/lib/postgresql/data:Z
    env_file:
      - .env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: lscr.io/linuxserver/nextcloud:latest
    restart: always
    volumes:
      - ${NEXTCLOUD_STACK_DIR}/app:/config
      - ${NEXTCLOUD_DATA_HOST_DIR}:/data
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - 8080:443
