

services:
  db:
    container_name: nextcloud_db
    image: postgres:alpine
    restart: always
    volumes:
      - ${NEXTCLOUD_STACK_DIR}/db:/var/lib/postgresql/data:Z
    env_file:
      - .env

  redis:
    container_name: nextcloud_redis
    image: redis:alpine
    restart: always

  app:
    container_name: nextcloud_app
    image: lscr.io/linuxserver/nextcloud:latest
    restart: always
    volumes:
      - ${NEXTCLOUD_STACK_DIR}/app:/var/www/html:z
      - ${NEXTCLOUD_DATA_HOST_DIR}:${NEXTCLOUD_DATA_DIR}:z
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - .env
    depends_on:
      - db
      - redis

